site_name: SimplCommerce Docs
theme: readthedocs
repo_url: https://github.com/simplcommerce/docs
google_analytics: ['UA-78132767-3', 'docs.simplcommerce.com']
pages:
- Introduction: index.md
- Getting started: getting-started.md
- Development tips: development-tips.md
- Internal structure of a module: internal-structure-of-a-module.md
- How to add new modules: how-to-add-new-modules.md
- How to add new payment providers: how-to-add-new-payment-providers.md
- How to add new languages: how-to-add-new-languages.md
- Theme development: theme-development.md
- Widgets: widgets.md
- How to use StorageAmazonS3 module: amazon-s3.md


