site_name: SimplCommerce Docs
pages:
- Introduction: index.md
- Getting started: getting-started.md
- Development tips: development-tips.md
- Internal structure of a module: internal-structure-of-a-module.md
- How to add new modules: how-to-add-new-modules.md
- How to add new lanuages: how-to-add-new-languages.md
- Theme development: theme-development.md
- Widgets: widgets.md
theme: readthedocs
repo_url: https://github.com/simplcommerce/docs/
google_analytics: ['UA-78132767-3', 'docs.simplcommerce.com']

